# Workflows

name: Multiple Commands

on:
  push: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Starting workflow"
      - run: echo "Runnign tests"
      - run: echo "Workflow completed"
