# It gives a name to the workflows, If omitted Github uses the workflow file name
name: Linux Commands
# It defines where to run the workflow
on:
  push:
    branches: [main]
    workflow_dispatch:
# It is a collection of steps that executes on a runner
jobs:
  linux-commands-practice: #job name
    runs-on: ubuntu-latest #Tells the github to run the job on a ubuntu
    # Individual tasks inside a job
    steps:
      - name: Trying the commands 
      #executes the shell commands
        run: pwd
        run: ls -l
        run: uname -r
